global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
    - name: webhook_receiver
      webhook_configs:
        - url: 'https://webhook.site/8f062bd0-626c-42fc-85ee-1970fc4fb00b'
          send_resolved: false